name: slovingo
description: "Dive into the delightful world of Slovene with Slovingo, your personal AI-powered language tutor that makes learning fun, interactive, and super efficient!"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  sqflite: ^2.0.0
  path: ^1.0.0
  provider: ^6.0.0
  go_router: ^17.0.0
  http: ^1.0.0
  shared_preferences: ^2.0.0
  intl: 0.20.2
  flutter_dotenv: ^5.1.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/1.jpg
  remove_alpha_ios: true
